apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fleet-helm-generator
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/jemmy8oy/oke-fleet.git
        revision: HEAD
        files:
          - path: "config/*.json"
  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: HEAD
        path: '{{chartPath}}' 
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{targetNamespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true # Keeps your OKE cluster safe from the 256KB metadata bug
