apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-fleet-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jemmy8oy/oke-fleet.git
    targetRevision: HEAD
    path: apps-root
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
